# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Core\MessengerBundle\MessageHandler\AnalyticsHandler:
    tags: [messenger.message_handler]