# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Core\Component\Storage\FileSystem\Model\JsonManager:
    class: Core\Component\Storage\FileSystem\Model\JsonManager
    arguments:
      $storagePath: '%storage_dir%'

  Core\Component\Storage\FileSystem\Model\JsonStorage:
    class: Core\Component\Storage\FileSystem\Model\JsonStorage
    arguments:
      $manager: '@Core\Component\Storage\FileSystem\Model\JsonManager'

  Core\Component\Storage\StorageInterface: '@Core\Component\Storage\FileSystem\Model\JsonStorage'

  Core\Component\Request\JsonConverter: ~